#!/usr/bin/env bun
// Regenerates src/pdf/logo-data.generated.ts from apps/web/public/logo.png so the logo is
// embedded as bytes (no runtime fs/cwd dependency). Re-run after changing logo.png.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const sourcePath = path.resolve(import.meta.dirname, "../../../apps/web/public/logo.png");
const outputPath = path.resolve(import.meta.dirname, "../src/pdf/logo-data.generated.ts");

const base64 = readFileSync(sourcePath).toString("base64");

writeFileSync(
  outputPath,
  `// AUTO-GENERATED by packages/api/scripts/generate-logo-data.ts — do not edit by hand.
// Source of truth: apps/web/public/logo.png
export const LOGO_PNG_BASE64 = "${base64}";
`,
);

console.log(`Wrote ${outputPath} (${base64.length} base64 chars, source ${sourcePath})`);
